name: "face-id"

services:
  server:
    build:
      dockerfile: containers/server/Dockerfile
    # command: >
    #   sh -c "uvicorn src.main:app --host 0.0.0.0 --port 80 --reload"
    volumes:
      - .:/var/backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/var/backend
      - static_volume:/var/backend/static

  # webrtc-redis-server:
  #   image: "redis:alpine"

    
volumes:
  static_volume: