name: Demo Worflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello ACTIONS
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load all the files
        uses: actions/checkout@v3

      # - name: Install docker compose
      #   uses: docker/compose-cli-action@v0.6.0
      #   with: 
      #     compose-version: 2.x
        
      - name: Build compose YAML
        run: |
          docker compose build
          docker compose up 
          docker compose ps
          docker compose down

      

        
    
    
