name: Demo Worflow
on: workflow_dispatch
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello ACTIONS
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Load all the files
        uses: actions/checkout@v3

      - name: Build docker compose
        run: |
          docker compose build
          docker compose up -d
          
      - name: Run tests
        run: |
          docker compose ps
          echo Running tests

      - name: Stop compose
        run: docker compose down

      

        
    
    
